service: datareal-repot
frameworkVersion: ^2.25

plugins:
  - serverless-prune-plugin

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: dev
  environment:
    SLACK_WEBHOOK_REPORTS: ${env:SLACK_WEBHOOK_REPORTS}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource:
            - ${self:custom.crawlerUniqueRawdataTableArn}
        # - Effect: Allow
        #   Action:
        #     - dynamodb:Query
        #   Resource:
        #     - ${self:custom.crawlerRawdataTableArn}
        #     - Fn::Join:
        #       - "/"
        #       -
        #         - ${self:custom.crawlerRawdataTableArn}
        #         - "index/*"

package:
  exclude:
    - ./**
  include:
    - ./dist/**

functions:
  share:
    handler: dist/lambda/share
    events:
      - httpApi:
          path: /share
          method: post
  create:
    handler: dist/lambda/create
    timeout: 900

custom:
  prune:
    automatic: true
    number: 3
  crawlerUniqueRawdataTableName: "datareal-crawler-unique-rawdata"
  crawlerUniqueRawdataTableArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.crawlerUniqueRawdataTableName}